<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Ejercicios TAE-2019-2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">Capitulo IV</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>




</div>


<div id="section" class="section level1 tabset tabset-fade tabset-pills">
<h1></h1>
<div id="punto-10" class="section level2">
<h2>Punto 10</h2>
<ul>
<li><strong>Estas pregunta deben respoderse utilizando el conjunto de datos <em>Weekly</em>, que es parte del paquete <em>ISLR</em>. Estos datos son similares en naturaleza a datos de <em>Smarket</em> de este capítulo, excepto que contiene 1,089 Regresos semanales durante 21 años, desde principios de 1990 hasta el final del 2010.</strong></li>
</ul>
<p><strong>(a) Produzaca algunos resumenes numéricos y gráficos de los datos <em>Weekly</em>.¿ parace que hay patrones?.</strong></p>
<blockquote>
<p>Resumen de variables:</p>
</blockquote>
<pre class="r"><code>library(ISLR)
data(&quot;Weekly&quot;)
summary(Weekly)</code></pre>
<pre><code>##       Year           Lag1               Lag2               Lag3         
##  Min.   :1990   Min.   :-18.1950   Min.   :-18.1950   Min.   :-18.1950  
##  1st Qu.:1995   1st Qu.: -1.1540   1st Qu.: -1.1540   1st Qu.: -1.1580  
##  Median :2000   Median :  0.2410   Median :  0.2410   Median :  0.2410  
##  Mean   :2000   Mean   :  0.1506   Mean   :  0.1511   Mean   :  0.1472  
##  3rd Qu.:2005   3rd Qu.:  1.4050   3rd Qu.:  1.4090   3rd Qu.:  1.4090  
##  Max.   :2010   Max.   : 12.0260   Max.   : 12.0260   Max.   : 12.0260  
##       Lag4               Lag5              Volume       
##  Min.   :-18.1950   Min.   :-18.1950   Min.   :0.08747  
##  1st Qu.: -1.1580   1st Qu.: -1.1660   1st Qu.:0.33202  
##  Median :  0.2380   Median :  0.2340   Median :1.00268  
##  Mean   :  0.1458   Mean   :  0.1399   Mean   :1.57462  
##  3rd Qu.:  1.4090   3rd Qu.:  1.4050   3rd Qu.:2.05373  
##  Max.   : 12.0260   Max.   : 12.0260   Max.   :9.32821  
##      Today          Direction 
##  Min.   :-18.1950   Down:484  
##  1st Qu.: -1.1540   Up  :605  
##  Median :  0.2410             
##  Mean   :  0.1499             
##  3rd Qu.:  1.4050             
##  Max.   : 12.0260</code></pre>
<blockquote>
<p>Matriz de gráfico de dispersión:</p>
</blockquote>
<pre class="r"><code>pairs(Weekly)</code></pre>
<p><img src="capitulo-IV_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>En la primera matriz muestra un resumen de las variables a trabajar, observamos que todas estan a una misma escala, ecepto la varible dirección que cuenta con dos niveles (Alto y bajo). En la segunda matriz las varibles lag1,lag2,lag3,lag4,lag5 y volumen, son variables que entre ellas aparentemente las observaciones se concentrar en el centro; podemos notar que las varible año y variable volume tiene un comportamiento de un polinomio de grado dos acsendente mientras pasa el tiempo.</p>
<blockquote>
<p>Matriz de correlaciones</p>
</blockquote>
<pre class="r"><code>cor(Weekly[,-9])</code></pre>
<pre><code>##               Year         Lag1        Lag2        Lag3         Lag4
## Year    1.00000000 -0.032289274 -0.03339001 -0.03000649 -0.031127923
## Lag1   -0.03228927  1.000000000 -0.07485305  0.05863568 -0.071273876
## Lag2   -0.03339001 -0.074853051  1.00000000 -0.07572091  0.058381535
## Lag3   -0.03000649  0.058635682 -0.07572091  1.00000000 -0.075395865
## Lag4   -0.03112792 -0.071273876  0.05838153 -0.07539587  1.000000000
## Lag5   -0.03051910 -0.008183096 -0.07249948  0.06065717 -0.075675027
## Volume  0.84194162 -0.064951313 -0.08551314 -0.06928771 -0.061074617
## Today  -0.03245989 -0.075031842  0.05916672 -0.07124364 -0.007825873
##                Lag5      Volume        Today
## Year   -0.030519101  0.84194162 -0.032459894
## Lag1   -0.008183096 -0.06495131 -0.075031842
## Lag2   -0.072499482 -0.08551314  0.059166717
## Lag3    0.060657175 -0.06928771 -0.071243639
## Lag4   -0.075675027 -0.06107462 -0.007825873
## Lag5    1.000000000 -0.05851741  0.011012698
## Volume -0.058517414  1.00000000 -0.033077783
## Today   0.011012698 -0.03307778  1.000000000</code></pre>
<p><strong>(b) Utilice el conjunto de datos completo para realizar una regresion logística con <em>Direction</em> como la respuesta y la cinco varibles de retraso mas <em>Volume</em> como predictoras. Use la funcion summary para imprimir los resultados. ¿algunos de los predictores parece ser estadisticamente significativos? si es asi ¿cuales son estas variables? </strong></p>
<blockquote>
<p>Resumen Regresión logística</p>
</blockquote>
<pre class="r"><code>mod1 &lt;- glm( Direction ~ Lag1+Lag2+Lag3+Lag4+Lag5+Volume,data = Weekly,family = &quot;binomial&quot;)
summary(mod1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + 
##     Volume, family = &quot;binomial&quot;, data = Weekly)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6949  -1.2565   0.9913   1.0849   1.4579  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  0.26686    0.08593   3.106   0.0019 **
## Lag1        -0.04127    0.02641  -1.563   0.1181   
## Lag2         0.05844    0.02686   2.175   0.0296 * 
## Lag3        -0.01606    0.02666  -0.602   0.5469   
## Lag4        -0.02779    0.02646  -1.050   0.2937   
## Lag5        -0.01447    0.02638  -0.549   0.5833   
## Volume      -0.02274    0.03690  -0.616   0.5377   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1496.2  on 1088  degrees of freedom
## Residual deviance: 1486.4  on 1082  degrees of freedom
## AIC: 1500.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Podemos observar que la variable Lag2 con un <strong>P-valor</strong> de 0.0296 es estadisiticamente significativa con un nivel de confianza de 0.05.</p>
<p><strong>(c) Compute la matrix de confusión y la fracción general de las predicciones correctas. Explica qué te dice la matriz de confusión logística.</strong></p>
<blockquote>
<p>Tabla de confusión</p>
</blockquote>
<pre class="r"><code>prediction &lt;- mod1$fitted.values
pred&lt;- rep(&quot;Dow&quot;,length(prediction))
pred[prediction &gt; 0.5]&lt;- &quot;Up&quot;
table(pred,Weekly$Direction)</code></pre>
<pre><code>##      
## pred  Down  Up
##   Dow   54  48
##   Up   430 557</code></pre>
<p>Con esta tabla de confusión y los datos de pruba, podemos concluir que el porcentaje de acierto en la prediccion es de <span class="math inline">\(\frac{54+557}{1089} = 0.5610 \times 100\)</span> = 56.10% del tiempo . La tasa de error con los datos de entrenamiento es del 100%-56.10% = 43.8%. Tambien apreciamos que cuando el mercado sube, El modelo acierta <span class="math inline">\(\frac{557}{48+557}=0.92\times100%\)</span>=92% de la veces, tambien cuando el mercado baja el modelo acierta un <span class="math inline">\(\frac{54}{54+430}=0.1115\times 100\)</span> = 11.15% del tiempo.</p>
<p><strong>(d) Ahora ajuste el modelo de regresión logística utilizando un período de datos de entrenamiento de 1990 a 2008, con Lag2 como el unico predictor. Calcule la matriz de confusión y la fracción general de las predicciones correctas para los datos retenidos (Es decir, los datos de 2009 y 2010)</strong></p>
<blockquote>
<p>Resumen Modelo con lag2.</p>
</blockquote>
<pre class="r"><code>train &lt;- subset.data.frame(x = Weekly,subset = Year &lt; 2009)
test2009_2010 &lt;- subset.data.frame(Weekly,subset = Year &gt;=2009)
mod2 &lt;- glm(Direction ~ Lag2 ,data = train,family = binomial)
summary(mod2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Direction ~ Lag2, family = binomial, data = train)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.536  -1.264   1.021   1.091   1.368  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  0.20326    0.06428   3.162  0.00157 **
## Lag2         0.05810    0.02870   2.024  0.04298 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1354.7  on 984  degrees of freedom
## Residual deviance: 1350.5  on 983  degrees of freedom
## AIC: 1354.5
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<blockquote>
<p>Tabla de confusión</p>
</blockquote>
<pre class="r"><code>prediction2 &lt;- predict(object = mod2,newdata = test2009_2010,type = &quot;response&quot;)
pred2&lt;- rep(&quot;Dow&quot;,length(prediction2))
pred2[prediction2 &gt; 0.5]&lt;- &quot;Up&quot;
table(pred2,test2009_2010$Direction)</code></pre>
<pre><code>##      
## pred2 Down Up
##   Dow    9  5
##   Up    34 56</code></pre>
<p>Con esta tabla de confusión y los datos de pruba, podemos concluir que el porcentaje de acierto en la prediccion es de <span class="math inline">\(\frac{9+56}{104}=0.625\times 100\)</span>= 62.5% del tiempo. La tasa de error con los datos de prueba es del 100%-62.5% = 37.5%. Tambien apreciamos que cuando el mercado sube, El modelo acierta <span class="math inline">\(\frac{56}{5+56}=0.9180\times100%\)</span>=91.8% del tiempo, tambien cuando el mercado baja el modelo acierta un <span class="math inline">\(\frac{34}{34+9}=0.79\times 100\)</span> = 79.6% del tiempo.</p>
<p><strong>(e) Repita (d) usando LDA</strong></p>
<blockquote>
<p>Resumen modelo LDA:</p>
</blockquote>
<pre class="r"><code>library(MASS)
modlda &lt;- lda(Direction~Lag2,data = train)
modlda</code></pre>
<pre><code>## Call:
## lda(Direction ~ Lag2, data = train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581
## 
## Coefficients of linear discriminants:
##            LD1
## Lag2 0.4414162</code></pre>
<blockquote>
<p>Tabla de confusión:</p>
</blockquote>
<pre class="r"><code>prediction_LDA &lt;- predict(object = modlda,newdata = test2009_2010)
table(prediction_LDA$class,test2009_2010$Direction)</code></pre>
<pre><code>##       
##        Down Up
##   Down    9  5
##   Up     34 56</code></pre>
<p>Con esta tabla de confusión y los datos de pruba, podemos concluir que el porcentaje de acierto en la prediccion es de <span class="math inline">\(\frac{9+56}{104}=0.625\times 100\)</span>= 62.5% del tiempo. La tasa de error con los datos de prueba es del 100%-62.5% = 37.5%. Tambien apreciamos que cuando el mercado sube, El modelo acierta <span class="math inline">\(\frac{56}{5+56}=0.9180\times100%\)</span>=91.8% de la veces, tambien cuando el mercado baja el modelo acierta un <span class="math inline">\(\frac{34}{34+9}=0.79\times 100\)</span> = 79.6% del tiempo.</p>
<p><strong>(f) Repita (d) usando QDA</strong></p>
<blockquote>
<p>Resumen modelo QDA</p>
</blockquote>
<pre class="r"><code>mod_QDA &lt;-  qda(Direction~Lag2,data = train)
mod_QDA</code></pre>
<pre><code>## Call:
## qda(Direction ~ Lag2, data = train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581</code></pre>
<pre class="r"><code>prediction_QDA &lt;- predict(mod_QDA,newdata = test2009_2010)
table(prediction_QDA$class,test2009_2010$Direction)</code></pre>
<pre><code>##       
##        Down Up
##   Down    0  0
##   Up     43 61</code></pre>
<p>Con esta tabla de confusión y los datos de pruba, podemos concluir que el porcentaje de acierto en la prediccion es de <span class="math inline">\(\frac{0+61}{104}=0.5865 \times 100\)</span>= 58.65% del tiempo. La tasa de error con los datos de prueba es del 100%-58.65% = 41.35%. Tambien apreciamos que cuando el mercado sube, El modelo acierta <span class="math inline">\(\frac{61}{61}=1\)</span> osea el 100% de la veces, Se resalta este modelo de anialisis de discriminación cudratica elige una dirección alta todo el tiempo.</p>
<p><strong>(g) Repita (d) usando Knn con k=1.</strong></p>
<blockquote>
<p>Table de confusión:</p>
</blockquote>
<pre class="r"><code>library(class)
train.x &lt;- as.matrix(train$Lag2)
test.x &lt;- as.matrix(test2009_2010$Lag2)
train.Direction &lt;- train$Direction
set.seed(1)
prediction_knn &lt;- knn(train = train.x,test = test.x,cl = train.Direction,k = 1)
table(prediction_knn,test2009_2010$Direction)</code></pre>
<pre><code>##               
## prediction_knn Down Up
##           Down   21 30
##           Up     22 31</code></pre>
<p>Con esta tabla de confusión y los datos de pruba, podemos concluir que el porcentaje de acierto en la prediccion es de 62.5% del tiempo. La tasa de error con los datos de prueba es del 100%-56.10% = 43.9%. Tambien apreciamos que cuando el mercado sube, El modelo acierta 50.81% de la veces, tambien cuando el mercado baja el modelo acierta un 48.83% del tiempo.</p>
<p><strong>(h) ¿ cuál de estos métodos parece proporcionar los mejores resultados con estos datos ?</strong></p>
<p>Con los modelos anteriores, vemos que el <em>modelo de regresión logístico</em> y <em>LDA</em>, La tasa de error es mínima. tambien para los modelos <em>QDA</em> y <em>KNN</em> un poco menores.</p>
<p><strong>(i) Experimente con diferentes combinaciones de predictores, incluyendo posibles transformaciones, para cada uno de los métodos, reporte la variables,método y la matriz de confusión asociada que parece proporcionar los mejores resultados en los mejores resultados en los datos retenidos.Tenga encuenta también debe experimentar con los valores para <em>K</em> en la clasificación con KNN. </strong></p>
<p>La variable mas significativa es Lag2 como se mostro en los anteriores puntos para tener una interacción con las segunda varible significativa.</p>
<pre class="r"><code>library(MASS)
library(class)

mod_inter_1 &lt;- glm(Direction~Lag2:Lag1,family = binomial,data = train)
prediction_inter_1 &lt;- predict(mod_inter_1,test2009_2010,type = &quot;response&quot;)
pred_inter_1 &lt;- rep(&quot;Dow&quot;,length(prediction_inter_1))
pred_inter_1[prediction_inter_1 &gt; 0.5] &lt;- &quot;Up&quot;


mod_lda_inter &lt;-lda(Direction~Lag2:Lag1,data = train)

prediction_LDA_inter &lt;- predict(mod_lda_inter,test2009_2010)


mod_QDA_inter &lt;- qda(Direction ~ Lag2+sqrt(abs(Lag2)),train)
pred_QDA_inter &lt;- predict(mod_QDA_inter,test2009_2010)

set.seed(0511)
#knn k=10
prediction_knn1 &lt;- knn(train = train.x,test = test.x,cl = train.Direction,k = 10)
#knn=100
prediction_knn2 &lt;- knn(train = train.x,test = test.x,cl = train.Direction,k = 100)</code></pre>
<blockquote>
<p><strong>Tablas de modelos realizados con interacciones</strong></p>
</blockquote>
<table>
<thead>
<tr class="header">
<th>Modelo</th>
<th>predicción correcta</th>
<th>tasa de presición cuando el mercado aumenta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>regresión logistica con interacción</td>
<td>57.69%</td>
<td>98.36%</td>
</tr>
<tr class="even">
<td>LDA con interacción</td>
<td>57.69%</td>
<td>98.36%%</td>
</tr>
<tr class="odd">
<td>QDA con <span class="math inline">\(\sqrt(abs(Lag2))\)</span></td>
<td>57.69%</td>
<td>78.68%</td>
</tr>
<tr class="even">
<td>knn con K=10</td>
<td>57.69%</td>
<td>68.85%</td>
</tr>
<tr class="odd">
<td>Knn con k=100</td>
<td>56.73%</td>
<td>80.32%</td>
</tr>
</tbody>
</table>
<p>De esta tabla se puede concluir que el modelo de regresión logística y LDA tienen el mejor rendimiento en tasas de error de prueba.</p>
</div>
<div id="punto-11" class="section level2">
<h2>Punto 11</h2>
<ul>
<li><strong>En este problema, desarrollará un modelo para predecir si un automóvil determinado obtiene un consumo de combustible alto o bajo en función del conjunto de datos automático.</strong></li>
</ul>
<p><strong>(a) Cree una variable binaria, mpg01, que contenga un 1 si mpg contiene un valor por encima de su mediana, y un 0 si mpg contiene un valor por debajo de su mediana. Puede calcular la mediana utilizando la función median(). Tenga en cuenta que puede resultarle útil utilizar la función data.frame() para crear un único conjunto de datos que contenga tanto mpg01 como las otras variables automáticas.</strong></p>
<pre class="r"><code>library(ISLR)
n &lt;- length(Auto$mpg)
mpg01 &lt;- ifelse( Auto$mpg &gt; median(Auto$mpg),1,0)
Auto &lt;- data.frame(Auto,mpg01)</code></pre>
<pre class="r"><code>knitr::kable(head(Auto),caption = &quot;Cabeza de base de datos Auto con variable mpg01&quot;)</code></pre>
<table>
<caption>Cabeza de base de datos Auto con variable mpg01</caption>
<thead>
<tr class="header">
<th align="right">mpg</th>
<th align="right">cylinders</th>
<th align="right">displacement</th>
<th align="right">horsepower</th>
<th align="right">weight</th>
<th align="right">acceleration</th>
<th align="right">year</th>
<th align="right">origin</th>
<th align="left">name</th>
<th align="right">mpg01</th>
<th align="right">mpg01.1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">18</td>
<td align="right">8</td>
<td align="right">307</td>
<td align="right">130</td>
<td align="right">3504</td>
<td align="right">12.0</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">chevrolet chevelle malibu</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">15</td>
<td align="right">8</td>
<td align="right">350</td>
<td align="right">165</td>
<td align="right">3693</td>
<td align="right">11.5</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">buick skylark 320</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">18</td>
<td align="right">8</td>
<td align="right">318</td>
<td align="right">150</td>
<td align="right">3436</td>
<td align="right">11.0</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">plymouth satellite</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="right">8</td>
<td align="right">304</td>
<td align="right">150</td>
<td align="right">3433</td>
<td align="right">12.0</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">amc rebel sst</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="right">8</td>
<td align="right">302</td>
<td align="right">140</td>
<td align="right">3449</td>
<td align="right">10.5</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">ford torino</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">15</td>
<td align="right">8</td>
<td align="right">429</td>
<td align="right">198</td>
<td align="right">4341</td>
<td align="right">10.0</td>
<td align="right">70</td>
<td align="right">1</td>
<td align="left">ford galaxie 500</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>(b) Explore los datos gráficamente para investigar la asociación entre mpg01 y las otras características. ¿Cuál de las otras características parece más útil para predecir mpg01? Los diagramas de dispersión y los diagramas de caja pueden ser herramientas útiles para responder a esta pregunta. Describe tus hallazgos.</strong></p>
<blockquote>
<p>Correlaciones entre variables:</p>
</blockquote>
<pre class="r"><code>cor(Auto[,-9])</code></pre>
<pre><code>##                     mpg  cylinders displacement horsepower     weight
## mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
## cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
## displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
## horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
## weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
## acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
## year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
## origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
## mpg01         0.8369392 -0.7591939   -0.7534766 -0.6670526 -0.7577566
## mpg01.1       0.8369392 -0.7591939   -0.7534766 -0.6670526 -0.7577566
##              acceleration       year     origin      mpg01    mpg01.1
## mpg             0.4233285  0.5805410  0.5652088  0.8369392  0.8369392
## cylinders      -0.5046834 -0.3456474 -0.5689316 -0.7591939 -0.7591939
## displacement   -0.5438005 -0.3698552 -0.6145351 -0.7534766 -0.7534766
## horsepower     -0.6891955 -0.4163615 -0.4551715 -0.6670526 -0.6670526
## weight         -0.4168392 -0.3091199 -0.5850054 -0.7577566 -0.7577566
## acceleration    1.0000000  0.2903161  0.2127458  0.3468215  0.3468215
## year            0.2903161  1.0000000  0.1815277  0.4299042  0.4299042
## origin          0.2127458  0.1815277  1.0000000  0.5136984  0.5136984
## mpg01           0.3468215  0.4299042  0.5136984  1.0000000  1.0000000
## mpg01.1         0.3468215  0.4299042  0.5136984  1.0000000  1.0000000</code></pre>
<blockquote>
<p>Grafico de dispersion</p>
</blockquote>
<pre class="r"><code>pairs(Auto)</code></pre>
<p><img src="capitulo-IV_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>attach(Auto)</code></pre>
<pre><code>## The following object is masked _by_ .GlobalEnv:
## 
##     mpg01</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 3):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 4):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 5):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 6):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 7):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 8):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 9):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 10):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 11):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 12):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 13):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 14):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 15):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 16):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 17):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 18):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 19):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     mpg01.1, name, origin, weight, year</code></pre>
<pre><code>## The following objects are masked from Auto (pos = 20):
## 
##     acceleration, cylinders, displacement, horsepower, mpg, mpg01,
##     name, origin, weight, year</code></pre>
<pre class="r"><code>layout(rbind(c(1,1,1,2,2,2,3,3,3),c(4,4,4,5,5,5,6,6,6)))
boxplot(cylinders~mpg01,data = Auto,main=&quot;Cilindros vs mpg01&quot;)
boxplot(displacement ~mpg01,data = Auto,main=&quot;Desplazamiento vs mpg01&quot;)
boxplot(horsepower ~mpg01,data = Auto,main=&quot;Caballos de fuerza vs mpg01&quot;)
boxplot(weight ~mpg01,data = Auto,main=&quot;Peso del vehiculo vs mpg01&quot;)
boxplot(acceleration ~mpg01,data = Auto,main=&quot;Aceleración vs mpg01&quot;)
boxplot(year ~mpg01,data = Auto,main=&quot;Modelo vs mpg01&quot;)</code></pre>
<p><img src="capitulo-IV_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p><strong>(c) Divida los datos en un conjunto de entrenamiento y un conjunto de prueba.</strong></p>
<p><strong>(d) Realice LDA en los datos de entrenamiento para predecir mpg01 usando las variables que parecían más asociadas con mpg01 en (b). ¿Cuál es el error de prueba del modelo obtenido?</strong></p>
<p><strong>(e) Realice QDA en los datos de entrenamiento para predecir mpg01 usando las variables que parecían más asociadas con mpg01 en (b). ¿Cuál es el error de prueba del modelo obtenido?</strong></p>
<p><strong>(f) Realice una regresión logística en los datos de entrenamiento para predecir mpg01 usando las variables que parecían más asociadas con mpg01 en (b). ¿Cuál es el error de prueba del modelo obtenido?</strong></p>
<p><strong>(g) Realice KNN en los datos de entrenamiento, con varios valores de K, para predecir mpg01. Use solo las variables que parecían más asociadas con mpg01 en (b). ¿Qué errores de prueba obtienes? ¿Qué valor de K parece tener el mejor rendimiento en este conjunto de datos?</strong></p>
</div>
<div id="punto-12" class="section level2">
<h2>Punto 12</h2>
<ul>
<li><strong>Este problema implica escribir funciones.</strong></li>
</ul>
<p><strong>(a) Escriba una función, Power(), que imprima el resultado de elevar 2 a la tercera potencia. En otras palabras, su función debe calcular <span class="math inline">\(2^3\)</span> e imprimir los resultados.Sugerencia: recuerde que <span class="math inline">\(x^a\)</span> eleva x a la potencia a. Use la función print() para generar el resultado.</strong></p>
<p><strong>(b) Cree una nueva función, Power2(), que le permita pasar dos números, x y a, e imprima el valor de <span class="math inline">\(x^a\)</span>. Puede hacer esto comenzando su función con la línea</strong></p>
<p><strong>Power2 = function (x,a){ </strong></p>
<p><strong>Debería poder llamar a su función ingresando, por ejemplo,</strong></p>
<p><strong>Power2(3,8)</strong></p>
<p><strong>en la línea de comando. Esto debería generar el valor de <span class="math inline">\(3^8\)</span>, es decir, 6, 561.</strong></p>
<p><strong>(c) Usando la función Power2() que acaba de escribir, calcule <span class="math inline">\(10^3\)</span>, <span class="math inline">\(8^17\)</span> y <span class="math inline">\(131^3\)</span>.</strong></p>
<p><strong>(d) Ahora cree una nueva función, Power3(), que realmente devuelve el resultado x^a como un objeto R, en lugar de simplemente imprimirlo en la pantalla. Es decir, si almacena el valor x^a en un objeto llamado resultado dentro de su función, simplemente puede return() este resultado, utilizando la siguiente línea:</strong></p>
<p><strong>return(result)</strong></p>
<p><strong>La línea de arriba debe ser la última línea en su función, antes del símbolo}.</strong></p>
<p><strong>(e) Ahora, utilizando la función Power3 (), cree un plot de f(x) = <span class="math inline">\(x^2\)</span>. El eje x debe mostrar un rango de enteros del 1 al 10, y el eje y debería mostrar <span class="math inline">\(x^2\)</span>. Rotule los ejes apropiadamente y use un título apropiado para la figura. Considere mostrar el eje x, el eje y o ambos en la escala logarítmica. Puede hacerlo utilizando log = ‘‘ x’’, log = ‘‘ y’’ o log = ‘‘ xy’’ como argumentos de la función plot()</strong></p>
<p><strong>(f) Cree una función, PlotPower (), que le permite crear una gráfica de x contra x ^ a para un a fijo y para un rango de valores de x. Por ejemplo, si llamas</strong></p>
<p><strong>plotPower(1:10,3)</strong></p>
<p><strong>entonces se debe crear un gráfico con un eje x que tome valores 333 1,2, …, 10 y un eje y que toma los valores <span class="math inline">\(1^3\)</span>,<span class="math inline">\(2^3\)</span>, …, <span class="math inline">\(10^3\)</span>.</strong></p>
<div id="punto-13" class="section level3">
<h3>Punto 13</h3>
<p><strong>Utilizando el conjunto de datos de Boston, ajuste los modelos de clasificación para predecir si un suburbio determinado tiene una tasa de criminalidad superior o inferior a la mediana. Explore los modelos de regresión logística, LDA y KNN utilizando varios subconjuntos de predictores. Describe tus hallazgos.</strong></p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
